<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <div class="container">
            <?= $this->content ?>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>

        <script language = "javascript">
            (function($) {
                $(document).ready(function(){
                    var currentPage = 1;
                    $('li#previous').addClass('disabled').removeClass('enabled');
                    function loadPage(page) {
                        $.ajax({
                            url: '/ajax/load',
                            type: 'POST',
                            data: {
                                page: page
                            },
                            dataType: 'json',
                            async: true,

                            success: function (data, status) {
                                var tableBody = $('#main tbody');
                                tableBody.html('');

                                if (data.response.length < 10) {
                                    $('li#next').addClass('disabled').removeClass('enabled');
                                }
                                else {
                                    $('li#next').removeClass('disabled').addClass('enabled');
                                }

                                for (count = 0; count <= data.response.length; count++) {
                                    var entry = data.response[count];
                                    var emptyRow = $('<tr>' +
                                        '<td class="date"></td>' +
                                        '<td class="name"></td>' +
                                        '<td class="quantity"></td>' +
                                        '<td class="distance"></td>' +
                                        '</tr>');
                                    $(".date", emptyRow).html(entry.date);
                                    $(".name", emptyRow).html(entry.name);
                                    $(".quantity", emptyRow).html(entry.quantity);
                                    $(".distance", emptyRow).html(entry.distance);

                                    tableBody.append(emptyRow);
                                }
                            },
                            error: function (xhr, textStatus, errorThrown) {
                                alert('Ajax request failed.');
                            }
                        });
                    }

                    loadPage(currentPage);

                    $('li.enabled#previous').click(function(event) {
                        currentPage--;
                        if (currentPage === 1) {
                            $('li#previous').addClass('disabled').removeClass('enabled');
                        }
                        else {
                            $('li#previous').removeClass('disabled').addClass('enabled');
                        }
                        loadPage(currentPage);
                    });
                    $('li.enabled#next').click(function(event) {
                        currentPage++;
                        if (currentPage === 1) {
                            $('li#previous').addClass('disabled').removeClass('enabled');
                        }
                        else {
                            $('li#previous').removeClass('disabled').addClass('enabled');
                        }
                        loadPage(currentPage);
                    });
                });
            })(jQuery);
        </script>
    </body>
</html>
