<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container">
<a id="generateData" class="btn btn-lg btn-light" href="#">Сгенерировать данные</a>
</div>

<div class="container">
    <table id="main" class="table table-striped table-bordered">
        <thead>
        <tr>
            <th class="date">Дата</th>
            <th class="name">Название</th>
            <th class="quantity">Количество</th>
            <th class="distance">Расстояние</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
    <nav aria-label="Table navigation">
        <ul class="pagination justify-content-center">
            <li id="previous" class="page-item enabled">
                <a class="page-link" href="#" tabindex="-1">Предыдущая страница</a>
            </li>
            <li id="next" class="page-item enabled">
                <a class="page-link" href="#">Следующая страница</a>
            </li>
        </ul>
    </nav>
</div>