<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container">
<a id="generateData" class="btn btn-lg btn-light" href="#">Сгенерировать данные</a>
</div>

<div class="container">
    <table class="table table-striped table-bordered">
        <thead>
        <tr>
            <th>Дата</th>
            <th>Название</th>
            <th>Количество</th>
            <th>Расстояние</th>
        </tr>
        </thead>
    </table>
</div>